### ISSUE TITLE
Missing dependency package com.opencsv

### ISSUE THREAD

**Issue by renfei** [ip2location/ip2location-java#7]
Hello.

https://github.com/ip2location/ip2location-java/blob/adf0d22cd2b0d5b57bb6d2a9604b313d6fef8604/com/ip2location/Country.java#L10

https://github.com/ip2location/ip2location-java/blob/adf0d22cd2b0d5b57bb6d2a9604b313d6fef8604/com/ip2location/Region.java#L7

It seems that the dependency package com.opencsv is missing.

![image](https://user-images.githubusercontent.com/6532952/196889788-3004950a-c938-4bf4-9055-299c3aa7e08e.png)

**Comment by ip2location** [comment]
It's easier if you just use the IP2Location Maven https://search.maven.org/artifact/com.ip2location/ip2location-java which will automatically include all the dependencies. Just need to wait for the latest version to appear in the page.

Otherwise, you can download the dependency yourself at https://search.maven.org/artifact/com.opencsv/opencsv/5.7.0/jar
